import {
  css,
  claude, 
  cloudinary,
  edge,
  express,
  git,
  github,
  graphql,
  gsap,
  heroUI,
  html,
  javascript,
  mongo,
  motion,
  next,
  nextjs,
  nodejs,
  notion,
  openAI,
  postgresql,
  postman,
  reactRouter,
  react,
  shadcn,
  tailwindcss,
  tanstack,
  typescript,
  vercel,
  vite,
  vsCode,
  windsurf,
  zenBrowser,
  zustand,
} from "./assets/technologies";
import type { MinorProjectCardProps } from "./components/home/minor-project-card";
import type { ProjectCardProps } from "./components/home/project-card";

export const profile = {
  name: "Sharoon Shaleem",
  resume: "/Sharoon-Shaleem.pdf",
  resumeLink:
    "https://drive.google.com/file/d/18W8xMA8vyjzY1XjCGQn9HhEXvyWVAbY-/view?usp=sharing",
  email: "ssharoon166@gmail.com",
  emailLink: "mailto:ssharoon166@gmail.com",
  whatsapp: "+92-315-5417036",
  whatsappLink: "https://wa.me/923155417036",
  github: "https://github.com/Sharoon166",
  linkenIn: "https://www.linkedin.com/in/sharoon-shaleem-0a7a85226/",
  instagram: "https://www.instagram.com/sharoonshaleem/",
  meeting: "https://cal.com/sharoon-shaleem/30min",
};

export const technologiesCollection = {
  css: { name: "CSS", icon: css },
  claude: { name: "Claude", icon: claude },
  cloudinary: { name: "Cloudinary", icon: cloudinary },
  edge: { name: "Edge", icon: edge },
  express: { name: "Express", icon: express },
  git: { name: "Git", icon: git },
  github: { name: "GitHub", icon: github },
  graphql: { name: "GraphQL", icon: graphql },
  gsap: { name: "GSAP", icon: gsap },
  heroUI: { name: "Hero UI", icon: heroUI },
  html: { name: "HTML", icon: html },
  javascript: { name: "JavaScript", icon: javascript },
  mongodb: { name: "MongoDB", icon: mongo },
  motion: { name: "Motion", icon: motion },
  next: { name: "Next.js", icon: next },
  nextjs: { name: "Next.js", icon: nextjs },
  nodejs: { name: "Node.js", icon: nodejs },
  notion: { name: "Notion", icon: notion },
  chatgpt: { name: "ChatGPT", icon: openAI },
  postgresql: { name: "PostgreSQL", icon: postgresql },
  postman: { name: "Postman", icon: postman },
  reactrouter: { name: "React Router", icon: reactRouter },
  react: { name: "React", icon: react },
  shadcn: { name: "Shadcn", icon: shadcn },
  tailwindcss: { name: "Tailwind CSS", icon: tailwindcss },
  tanstackQuery: { name: "TanStack Query", icon: tanstack },
  typescript: { name: "TypeScript", icon: typescript },
  vercel: { name: "Vercel", icon: vercel },
  vite: { name: "Vite", icon: vite },
  vscode: { name: "VS Code", icon: vsCode },
  windsurf: { name: "Windsurf", icon: windsurf },
  zenBrowser: { name: "Zen Browser", icon: zenBrowser },
  zustand: { name: "Zustand", icon: zustand },
};

export const technologies: (keyof typeof technologiesCollection)[] = [
  "html",
  "css",
  "tailwindcss",
  "shadcn",
  "javascript",
  "typescript",
  "vite",
  "react",
  "reactrouter",
  "zustand",
  "motion",
  "express",
  "nodejs",
  "mongodb",
  "postgresql",
  "next",
  "tanstackQuery",
] as const;

export const tools: (keyof typeof technologiesCollection)[] = [
  "vscode",
  "windsurf",
  "git",
  "github",
  "postman",
  "vercel",
  "zenBrowser",
  "edge",
  "chatgpt",
  "claude",
] as const;

export const projects: ProjectCardProps[] = [{
  title: "Diniiz",
  description: "Restaurant management application with order, customer, and analytics features, built during work at Synctom. Includes realtime notifications, messaging, and reservation visualization on an interactive floor canvas 🤯",
  image: "/projects/diniiz.png",
  githubUrl: "",
  previewUrl: "https://diniiz.com",
  technologies: ["react", "reactrouter", "tailwindcss", "shadcn", "nodejs", "express", "mongodb", "cloudinary"],
  themeColor: "#0C9CDC",
},
{
  title: "Brake Time",
  description: "A powerful admin dashboard for Braketime's backoffice, streamlining employee records, customer data, and inventory management. 💼📊",
  githubUrl: "https://github.com/Sharoon166/brake-time",
  previewUrl: "https://brake-time.vercel.app",
  image: "/projects/brake-time.png",
  technologies: ["tailwindcss", "next", "heroUI"],
  themeColor: "#1ECF76",
},
{
  title: "Animadom",
  description:
    "Animadom is a sleek platform for anime lovers, offering genre-based exploration and detailed insights. 🎌✨ Dive into the world of anime with ease!",
  githubUrl: "https://github.com/Sharoon166/Animadom",
  previewUrl: "https://animadom.vercel.app",
  image: "/projects/animadom.png",
  technologies: ["tailwindcss", "shadcn", "reactrouter", "typescript", "graphql", "motion"],
  themeColor: "#00abc2",
},
{
  title: "Audix",
  description:
    "An interactive earbuds showcase with smooth animations and view-transitions. 🎧✨ Explore premium audio devices!",
  githubUrl: "https://github.com/Sharoon166/audix",
  previewUrl: "https://audixs.vercel.app/",
  image: "/projects/audix.png",
  technologies: ["tailwindcss", "next", "motion"],
  themeColor: "#9FDAEC",
},
{
  title: "Mangadom",
  description: "Discover and explore a vast collection of manga titles. Browse genres and dive into captivating stories from our extensive library. 📚✨",
  githubUrl: "https://github.com/Sharoon166/mangadom",
  previewUrl: "https://mangadom.vercel.app/",
  image: "/projects/mangadom.png",
  technologies: ["tailwindcss", "shadcn", "next"],
  themeColor: "#6B7280",
},
{
  title: "Voyager",
  description:
    "A sleek tourism website design, showcasing destinations, travel guides, and curated experiences for adventurers.",
  githubUrl: "https://github.com/Sharoon166",
  previewUrl: "https://voyagertravels.vercel.app",
  image: "/projects/voyager.png",
  technologies: ["html", "tailwindcss", "vite"],
  themeColor: "#CCF32F",
},
{
  title: "Samurai Systems",
  description:
    "A sleek, dark-themed landing page for a startup IT company, highlighting its expertise in cybersecurity, IT infrastructure, and digital transformation.",
  githubUrl: "https://github.com/Sharoon166/Samurai_Systems",
  previewUrl: "https://samurai-systems166.vercel.app/",
  image: "/projects/samurai-systems.png",
  technologies: ["next", "tailwindcss", "gsap"],
  themeColor: "#E74B4F",
},
{
  title: "Halal Devco.",
  description:
    "A sleek website for Halal DevCo, showcasing halal investment opportunities, industry growth, and sustainable innovation. ",
  githubUrl: "https://github.com/Sharoon166/halal_devco_frontend",
  previewUrl: "https://halal-devco.vercel.app/",
  image: "/projects/halal-devco.png",
  technologies: ["next", "tailwindcss"],
  themeColor: "#64B166",
},
];

export const minorProjects: MinorProjectCardProps[] = [{
  title: "Z Digitizing",
  description: "A modern portfolio showcasing 10+ years of unique embroidery designs and craftsmanship.",
  liveUrl: "https://z-digitizing.vercel.app/",
},{
  title: "DevHive",
  description: "A modern developer community platform where tech professionals can connect, share knowledge, and stay updated with the latest industry trends.",
  liveUrl: "https://devhsr.vercel.app/",
}];
